#!/bin/sh

if test -e "$HOME"/.config/ublue/firstboot-done; then
    echo "Already ran"
    exit 0
fi
w
(
echo "# Waiting for internet connection"
until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done
echo "00"

echo "# Setting OpenRGB defaults"
cp -r -f /usr/etc/home/config/OpenRGB/ ~/.config/ ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Failed to copy the OpenRGB defaults to your home directory."
        exit 1
fi
echo "2"

gith &

echo "# Adding Flathub repository"
/usr/bin/flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Failed to add Flathub as a Flatpak repo."
        exit 1
fi
echo "3"

echo "Removing all preinstalled Flatpaks"
/usr/bin/flatpak remove --system --noninteractive --all ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing all preinstalled Flatpaks failed"
        exit 1
fi

echo "# Removing Fedora Flatpak repository"
/usr/bin/flatpak remote-delete fedora --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Fedora Flatpak repo failed"
        exit 1
fi
echo "25"

echo "# Installing Firefox"
/usr/bin/flatpak install --user --noninteractive flathub org.mozilla.firefox
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Firefox failed"
        exit 1
fi
echo "30"

echo "# Installing Workspaces"
/usr/bin/flatpak install --user --noninteractive flathub com.github.devalien.workspaces
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Workspaces failed"
        exit 1
fi
echo "60"

echo "# Installing OnlyOffice"
/usr/bin/flatpak install --user --noninteractive flathub org.onlyoffice.desktopeditors
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing OnlyOffice failed"
        exit 1
fi
echo "70"

echo "# Installing Font Downloader"
/usr/bin/flatpak install --user --noninteractive flathub org.gustavoperedo.FontDownloader
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing FontDownloader failed"
        exit 1
fi
echo "85"

echo "# Installing Flatseal"
/usr/bin/flatpak install --user --noninteractive flathub com.github.tchx84.Flatseal
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Flatseal failed"
        exit 1
fi
echo "90"

echo "# Installing PDF Slicer"
/usr/bin/flatpak install --user --noninteractive flathub com.github.junrrein.PDFSlicer
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing PDF Slicer failed"
        exit 1
fi
echo "95"

echo "# Installing Popsicle USB Flasher"
/usr/bin/flatpak install --user --noninteractive flathub com.system76.Popsicle
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing System76 Popsicle failed"
        exit 1
fi
echo "100"

echo "# Reticulating Final Splines"
mkdir -p "$HOME"/.config/ublue/
touch "$HOME"/.config/ublue/firstboot-done
cp -n /etc/justfile "$HOME"/.justfile

) | 
     
   zenity --progress --title="Kinoite MSI Stealth 15m Desktop Firstboot" --percentage=0 --auto-close --no-cancel --width=300

if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Firstboot Configuration Error"
fi
